# Alembic script.py.mako template is auto-generated.
# This file is a Mako template.
# DO NOT MODIFY THIS FILE -- it is auto-generated by Alembic.

"""add bot tokens to workspace table

Revision ID: 2912a50f83f4
Revises: 002_add_workspace_fk
Create Date: 2025-12-22 12:50:01.933500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2912a50f83f4'
down_revision = '002_add_workspace_fk'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_standup_reports_user_id_date'), table_name='standup_reports')
    op.drop_constraint(op.f('standup_reports_user_id_report_date_key'), 'standup_reports', type_='unique')
    op.create_unique_constraint('uq_user_date', 'standup_reports', ['user_id', 'report_date'])
    op.drop_index(op.f('ix_standup_states_user_id'), table_name='standup_states')
    op.create_unique_constraint('uq_user_state', 'standup_states', ['user_id'])
    op.drop_index(op.f('ix_users_active'), table_name='users')
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.add_column('workspaces', sa.Column('bot_token', sa.String(length=255), nullable=True))
    op.add_column('workspaces', sa.Column('bot_user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'bot_user_id')
    op.drop_column('workspaces', 'bot_token')
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=False)
    op.create_index(op.f('ix_users_active'), 'users', ['active'], unique=False)
    op.drop_constraint('uq_user_state', 'standup_states', type_='unique')
    op.create_index(op.f('ix_standup_states_user_id'), 'standup_states', ['user_id'], unique=False)
    op.drop_constraint('uq_user_date', 'standup_reports', type_='unique')
    op.create_unique_constraint(op.f('standup_reports_user_id_report_date_key'), 'standup_reports', ['user_id', 'report_date'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_standup_reports_user_id_date'), 'standup_reports', ['user_id', 'report_date'], unique=False)
    # ### end Alembic commands ###
